### ISSUE TITLE
Nice minimalistic distro to be add on this list

### ISSUE THREAD

**Issue by terremoth** [muevoid/mue-linux#1]
https://docs.google.com/spreadsheets/d/1CK94VDeW0r4MCPIWgrM3AhVOc3dbZbMw96FW23xe36U/edit#gid=0

Tell me more about this distro, so I can fill those lines!

😎

**Comment by muevoid** [comment]
Most info is in the readme but I can say some things. Init system is currently busybox's init system however I am planning on switching to sinit as the default. The "default" wm is sway however no one is forces to install it. Currently using the ash shell. Working on docs but no docs atm. Package manager is currently the default kiss package manager however I have plans to rewrite it in c. userland is currently busybox but I am looking into sbase. Distro focus is on a simple hackable system that is also secure.

**Comment by terremoth** [comment]
No problem... and what about an "iso" image average size with sway? How much size it looks like in MB? And how many MB are required in hard disk to install Mue (with sway)?

**Comment by terremoth** [comment]
If you allow me some advices...
If you want Mue Linux grows, try to:

- [ ] My opinion: don't rewrite a package manager from zero.  If I were you, I would choose Void Linux xbps package manager, or proferably: Alpine Linux APK package manager. Both are very "minimal", "little", "suklessed", and both have a lot packages made (thousands!). Having a good and already done package manager with availables packages is something crucial when someone is going to choose a distro. It takes a lot of time to compile packages and almost no one likes to build from source and fight problems that appear in this process of build;
- [ ] make at least a little wiki, telling people your motivation to make a new distro and why, telling the history, etc and then teaching step by step how to download, burn/make a iso, how to install it and how to use basic things (such as install wayland+sway), connect to the internet (cable + wifi) etc;
- [ ] Try to make the distro available (as ISO) not just for 64 bits, but for 32 bits users and ARM users too, AT LEAST. Because you can  give the opportunity to people ship Mue in old computers (resurrect some of them!) and ship into single board computers for IOT - it is a world that runs on low resource usages and sometimes need things to be simple and fast (alpine packages can help you with that because they ship packages in a lot of architectures);
- [ ] make a telegram channel and a IRC channel for Mue, so the users can interact with each other, report bugs, share images, tips, help new users etc;

**Comment by terremoth** [comment]
If you need some help, I could try to help.  
I always wanted to create a usable Linux distro but with suckless userland and suckless softwares; There is sta.li linux, but as @garbeam told days ago: Sta.li is just an experiment and is not intended to use in production. I believe you **can** create a production ready, minimal, usable and suckless linux distro with Mue.

And as I told in the beginning, if you want help with something, let's talk about the things that needs to be done and where I can help, it is hard to do a lot of work on part time alone :-)

**Comment by muevoid** [comment]
My response to some of the first idead you had.

1. I know for a fact i'd like to stick with the kiss package manager. I would like to rewrite it in c however it will be able to use alread existing kiss packages. My reason for this choice is due to the fact that the kiss package manager is dead simple and fast. Writing package builds are as easy as writing shell scripts even void linux package manager is more complicates then the kiss one. This doesn't mean other ones are bad but the kiss package manager imo is the most sane choice for a minimalistic package manager. It is very similar to cruz linux build system.

2. I already have plans for a wiki in fact I plan on getting the website up and running soon for mue-linux. This will contain most of the things you suggested.

3. I do hope to be able to ship a 32 bit version and arm version of the root tarball however currently I do not have any devices to test those on. But I do have plans for this in the future.

4. I do not have telegram at the moment however I will definitely be making an irc channel.

To answer your first question currently instead of an iso it is a root tarball that requires another distros livecd to install but this will be changing very soon.

**Comment by terremoth** [comment]
The very big problem with kiss package manager, is because is not really a package manager, nor really deals with packages. It just automate things to compile from source. Take a look: https://github.com/kisslinux/repo/tree/master/xorg/libXdamage

You see: it is not really a package.

The source:
https://github.com/kisslinux/kiss/blob/master/kiss

You can see it just automates things to: download source, decompress, download dependencies, decompress, build first dependencies, and then build from source.

When you deal with real binary packages (real packages!) you don't need to do all that (compile from source). This is why I suggested you use xbps (void) or apk (alpine);

Also: kiss linux have no more than 100 ""packages"". If you want to install something different, you gonna need to build all yourself from source (as the its ""package manager"") but less automate.

**Comment by muevoid** [comment]
I believe that your ideas for what this distro should be and mine are different. Firstly let's address the "it's not a package manager". It is 100% a package manager it manages packages. It detects dependencies and handles downloading them, handles new versions and updating, etc. Secondly one of my goals is to compile from source. Binary packages don't allow you to customize as much as compiling from source I don't think it's fair to say source packages aren't real packages. Are gentoo packages not real packages? That's just nonsense. You also have obvisously done no research kiss has 100's of packages and growing. Sure still much less then other distros but due to the growing community there are plenty of repos to find what you need. And the beauty of the package manager is that anyone can package things.

**Comment by muevoid** [comment]
This issue is closed. I appreciate the suggestions but please do not try to convince me to switch to something else due to you not liking my choice. I do not mean to come off agressive.

**Comment by terremoth** [comment]
Relax. I think you misunderstood me. It was just suggestions. You do what you want! And who wants things different, can clone your repo and do different. That's the way it was always. I just suggested things that in my opinion could help to grow up a mue-linux community.

**Comment by muevoid** [comment]
I did not mean to come off agressive I agree i was in the wrong I apologize. I had sent that at around 4am my time and I hadn't slept in over a day so I was uneccessarly aggressive. I appreciate the suggestions and offers. To answer about the packages yes core only has a small number but when you add community, kiss-games, and the extra packages I am packaging it becomes many more packages albeit not all but definitely enough to get started. I may look into other options for package managers including possibly my own. We will see if you'd like to discuss further with me you can email me at muevoid@protonmail.com or I will be hopefully creating #muelinux on freenode soon. I'd love to discuss things further again I apologize for my uncessarcy agressiveness and hope you forgive me.

**Comment by muevoid** [comment]
@terremoth

**Comment by terremoth** [comment]
No problem man, relax. Everything cool. I will appear there (irc).
